name: Dotnet Build-Test-MSDeploy your project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:

  Build-Test-Deploy:
    runs-on: windows-latest
    env:
      PROJECT_DIRECTORY_PATH: "TestGithubActions"
      IIS_SERVER_COMPUTER_NAME: ${{ secrets.IIS_SERVER_COMPUTER_NAME }}
      IIS_WEBSITE_NAME: ${{ secrets.IIS_WEBSITE_NAME }}
      IIS_SERVER_USERNAME: ${{ secrets.IIS_SERVER_USERNAME }}
      IIS_SERVER_PASSWORD: ${{ secrets.IIS_SERVER_PASSWORD }}
      RECYCLE_APP_NAME: ${{ secrets.RECYCLE_APP_NAME }}
      WEBSITE_CONTENT_PATH: ${{ secrets.WEBSITE_CONTENT_PATH }}

    steps:
    - uses: actions/checkout@v2

    - name: Checking environment...
      uses: RahulParmarRP/dotnet-build-test-msdeploy@test